rivers = ['Nile', 'Ganga', 'Narmada', 'Jordan', 'Amazon']
rivers.append('Bramhaputra')
print(rivers)
print(rivers[1])
print(rivers[2].title())
print(rivers[-1])
rivers[2] = 'Yangtze'
print(rivers)
rivers.insert(2, 'Mississippi')
print(rivers)
del rivers[3]
largest = rivers.pop()
print(f"{largest} is the largest river.")
rivers.remove('Nile')
print(rivers)
rivers.sort()
print(rivers)
rivers.sort(reverse=True)
print(rivers)
print(sorted(rivers))
print(sorted(rivers, reverse = True))
print(rivers)
rivers.reverse()
print(rivers)
print(len(rivers))